spring.data.mongodb.uri=mongodb+srv://alvarosb01_db_user:Sobral123@cluster0.petwbiz.mongodb.net/wtc_db?retryWrites=true&w=majority&appName=Cluster0
spring.application.name=wtc
api.security.token.secret=${JWT_SECRET:minha-senha-super-secreta-123456}
spring.data.mongodb.database=wtc_db
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Configurações do  "S3 Local" (MinIO)
aws.access-key=minioadmin
aws.secret-key=minioadmin
aws.s3.endpoint=http://localhost:9000
aws.s3.bucket=wtc-attachments