spring.data.mongodb.uri=mongodb+srv://alvarosb01_db_user:Sobral123@cluster0.petwbiz.mongodb.net/wtc_db?retryWrites=true&w=majority&appName=Cluster0
<<<<<<< HEAD
spring.application.name=wtc
api.security.token.secret=${JWT_SECRET:minha-senha-super-secreta-123456}
=======
spring.data.mongodb.database=wtc_db
>>>>>>> SCRUM-14
