package com.wtc.conversation;

import com.wtc.auth.UserDocument;
import com.wtc.conversation.dto.ConversationResponse;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;

import java.time.Instant;

/**
 * Starts a brand-new OPEN conversation for an existing customer. Until now conversations
 * were only ever created during CLIENTE registration ({@code AuthService.register}), which
 * left CRM-created customers ({@code POST /customers}) with no way to be messaged. The id is
 * generated by MongoDB so a customer can hold more than one conversation over time.
 */
@Service
public class CreateConversationService {

    private final ConversationRepository conversationRepository;

    public CreateConversationService(ConversationRepository conversationRepository) {
        this.conversationRepository = conversationRepository;
    }

    public ConversationResponse execute(String customerId) {
        ConversationDocument conversation = new ConversationDocument();
        conversation.setCustomerId(customerId);
        conversation.setOperatorId(currentOperatorId());
        conversation.setStatus("OPEN");
        conversation.setUpdatedAt(Instant.now());

        ConversationDocument saved = conversationRepository.save(conversation);

        return new ConversationResponse(
                saved.getId(),
                saved.getCustomerId(),
                saved.getOperatorId(),
                saved.getStatus(),
                saved.getUpdatedAt()
        );
    }

    private String currentOperatorId() {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        if (auth != null && auth.getPrincipal() instanceof UserDocument user) {
            return user.getId();
        }
        return null;
    }
}
